######################################################################
##
## Thomas Ames
## ECEA 5305, assignment #2, Makefile for writer.c
## July 2023
##

CC = $(CROSS_COMPILE)gcc

all: writer

clean:
	rm -f writer *.o

writer: writer.o
